"""season_ratings

Revision ID: 9efcf46b8035
Revises: aebe3f972ba7
Create Date: 2026-06-28 04:41:37.585854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9efcf46b8035'
down_revision: Union[str, Sequence[str], None] = 'aebe3f972ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season_ratings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('show_id', sa.BigInteger(), nullable=False),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 10', name=op.f('ck_season_ratings_rating_range')),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name=op.f('fk_season_ratings_show_id_shows'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_season_ratings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_season_ratings')),
    sa.UniqueConstraint('user_id', 'show_id', 'season', name=op.f('uq_season_ratings_user_id'))
    )
    op.create_index('ix_season_ratings_user_show', 'season_ratings', ['user_id', 'show_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_season_ratings_user_show', table_name='season_ratings')
    op.drop_table('season_ratings')
    # ### end Alembic commands ###
