"""initial schema

Revision ID: aebe3f972ba7
Revises: 
Create Date: 2026-06-26 16:07:52.643845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aebe3f972ba7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tvmaze_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('poster_url', sa.Text(), nullable=True),
    sa.Column('premiered', sa.Date(), nullable=True),
    sa.Column('ended', sa.Date(), nullable=True),
    sa.Column('tvmaze_status', sa.Text(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('total_seasons', sa.SmallInteger(), nullable=True),
    sa.Column('total_episodes', sa.SmallInteger(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shows')),
    sa.UniqueConstraint('tvmaze_id', name=op.f('uq_shows_tvmaze_id'))
    )
    op.create_index('ix_shows_genres', 'shows', ['genres'], unique=False, postgresql_using='gin')
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('episodes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('show_id', sa.BigInteger(), nullable=False),
    sa.Column('tvmaze_episode_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.SmallInteger(), nullable=False),
    sa.Column('number', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('airdate', sa.Date(), nullable=True),
    sa.Column('runtime', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name=op.f('fk_episodes_show_id_shows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_episodes')),
    sa.UniqueConstraint('show_id', 'season', 'number', name=op.f('uq_episodes_show_id')),
    sa.UniqueConstraint('tvmaze_episode_id', name=op.f('uq_episodes_tvmaze_episode_id'))
    )
    op.create_index(op.f('ix_episodes_show_id'), 'episodes', ['show_id'], unique=False)
    op.create_table('user_shows',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('show_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), server_default='plan_to_watch', nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('watching', 'completed', 'dropped', 'plan_to_watch')", name=op.f('ck_user_shows_status_valid')),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name=op.f('fk_user_shows_show_id_shows'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_shows_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_shows')),
    sa.UniqueConstraint('user_id', 'show_id', name=op.f('uq_user_shows_user_id'))
    )
    op.create_index('ix_user_shows_user_status', 'user_shows', ['user_id', 'status'], unique=False)
    op.create_table('episode_watches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('episode_id', sa.BigInteger(), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], name=op.f('fk_episode_watches_episode_id_episodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_episode_watches_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_episode_watches')),
    sa.UniqueConstraint('user_id', 'episode_id', name=op.f('uq_episode_watches_user_id'))
    )
    op.create_index(op.f('ix_episode_watches_user_id'), 'episode_watches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episode_watches_user_id'), table_name='episode_watches')
    op.drop_table('episode_watches')
    op.drop_index('ix_user_shows_user_status', table_name='user_shows')
    op.drop_table('user_shows')
    op.drop_index(op.f('ix_episodes_show_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_table('users')
    op.drop_index('ix_shows_genres', table_name='shows', postgresql_using='gin')
    op.drop_table('shows')
    # ### end Alembic commands ###
