"""user_shows watch dates

Revision ID: e1c4b3a07dde
Revises: 9efcf46b8035
Create Date: 2026-06-28 13:41:30.663545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c4b3a07dde'
down_revision: Union[str, Sequence[str], None] = '9efcf46b8035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_shows', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_shows', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_shows', 'finished_at')
    op.drop_column('user_shows', 'started_at')
    # ### end Alembic commands ###
